# Generated by Django 5.0.6 on 2024-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_date",
        ),
        migrations.AddField(
            model_name="booking",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="flight_number",
            field=models.CharField(max_length=100),
        ),
    ]
